//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jquery.TService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TService.TooltipServiceSoap")]
    public interface TooltipServiceSoap {
        
        // CODEGEN: Generating message contract since element name fieldName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTooltip", ReplyAction="*")]
        jquery.TService.GetTooltipResponse GetTooltip(jquery.TService.GetTooltipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTooltip", ReplyAction="*")]
        System.Threading.Tasks.Task<jquery.TService.GetTooltipResponse> GetTooltipAsync(jquery.TService.GetTooltipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTooltipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTooltip", Namespace="http://tempuri.org/", Order=0)]
        public jquery.TService.GetTooltipRequestBody Body;
        
        public GetTooltipRequest() {
        }
        
        public GetTooltipRequest(jquery.TService.GetTooltipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTooltipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fieldName;
        
        public GetTooltipRequestBody() {
        }
        
        public GetTooltipRequestBody(string fieldName) {
            this.fieldName = fieldName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTooltipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTooltipResponse", Namespace="http://tempuri.org/", Order=0)]
        public jquery.TService.GetTooltipResponseBody Body;
        
        public GetTooltipResponse() {
        }
        
        public GetTooltipResponse(jquery.TService.GetTooltipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTooltipResponseBody {
        
        public GetTooltipResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TooltipServiceSoapChannel : jquery.TService.TooltipServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TooltipServiceSoapClient : System.ServiceModel.ClientBase<jquery.TService.TooltipServiceSoap>, jquery.TService.TooltipServiceSoap {
        
        public TooltipServiceSoapClient() {
        }
        
        public TooltipServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TooltipServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TooltipServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TooltipServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        jquery.TService.GetTooltipResponse jquery.TService.TooltipServiceSoap.GetTooltip(jquery.TService.GetTooltipRequest request) {
            return base.Channel.GetTooltip(request);
        }
        
        public void GetTooltip(string fieldName) {
            jquery.TService.GetTooltipRequest inValue = new jquery.TService.GetTooltipRequest();
            inValue.Body = new jquery.TService.GetTooltipRequestBody();
            inValue.Body.fieldName = fieldName;
            jquery.TService.GetTooltipResponse retVal = ((jquery.TService.TooltipServiceSoap)(this)).GetTooltip(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<jquery.TService.GetTooltipResponse> jquery.TService.TooltipServiceSoap.GetTooltipAsync(jquery.TService.GetTooltipRequest request) {
            return base.Channel.GetTooltipAsync(request);
        }
        
        public System.Threading.Tasks.Task<jquery.TService.GetTooltipResponse> GetTooltipAsync(string fieldName) {
            jquery.TService.GetTooltipRequest inValue = new jquery.TService.GetTooltipRequest();
            inValue.Body = new jquery.TService.GetTooltipRequestBody();
            inValue.Body.fieldName = fieldName;
            return ((jquery.TService.TooltipServiceSoap)(this)).GetTooltipAsync(inValue);
        }
    }
}
